---
title: ""
---

## **Education**
**Ph.D. Natural Resources & Environmental Studies**: 2021 - Present  
University of New Hampshire | Durham, NH
<br> 
<br>

**M.Sc. Biological Sciences**: 2018 - 2020  
California Polytechnic State University | San Luis Obispo, CA
<br>
<br>

**B.Sc. Biological Sciences**: 2010 - 2014  
California Polytechnic State University | San Luis Obispo, CA
<br>
<br>
<br>
<br>

## **Publications**
**Willems, J.S.**, J.N. Phillips, R.A. Vosbigian, F.X. Villablanca, & C.D. Francis. 2021. “Night lighting and anthropogenic noise alter the activity and body condition of pinyon mice (_Peromyscus truei_)”, Ecosphere 12(3): e03388, [https://doi.org/10.1002/ecs2.3388](https://doi.org/10.1002/ecs2.3388)
<br>
<br>

**Willems, J.S.**, J.N. Phillips, & C.D. Francis. 2021. “Artificial light at night and anthropogenic noise alter the foraging activity and structure of vertebrate communities”, Science of the Total Environment, 805,  [https://doi.org/10.1016/j.scitotenv.2021.150223](https://doi.org/10.1016/j.scitotenv.2021.150223)
<br>
<br>

Kleist, N.J., **Willems, J.S.**, Bencin, H.L., Foster, A.C., McCall, L.E., Meineke, J.K., Poor, E.E., & Carter, S.K. “Annotated Bibliography of Scientific Research on Pygmy Rabbits 1990 - 2020”, _In Review_
<br>
<br>
<br>
<br>

## **Work Experience**
**Graduate Researcher**: June 2021 - Present  
University of New Hampshire | Durham, NH  
<br>
_Responsibilities_: Lead a field crew on project investigating the effects of forest structure and resources availability on small mammal communities. Collected hair, tissue, and fecal samples from captured rodents and shrews. Conducted vegetation surveys to assess forest structure and sampled seed-fall to assess resource availability.

<br>
<br>

**Research Ecologist**: September 2020 - May 2021  
United States Geological Survey | Fort Collins, CO  
<br>
_Responsibilities_: Team member on collaboration with the BLM on integrating science into management practices. Worked on compiling and summarizing all relevant science for species of management priority and coordinated creation of annotated bibliography manuscripts for publication. Assessed utilization of science and data in BLM management decisions. Collaborated closely with land managers to identify priority science needs and support management decisions.

<br>
<br>

**Graduate Researcher**: September 2018 - August 2020  
California Polytechnic State University | San Luis Obispo, CA  
<br>
_Responsibilities_: Project lead for research on anthropogenic light and sound impacts on animal communities. Developed study design, organized field logistics, and implemented sampling protocols. Collected data on small mammals using physical trapping, radio telemetry, and camera traps. Installed and maintained telemetry receiver towers and artificial light stations. Supervised students and assisted in the development and implementation of artificial nest experiments. Utilized R, R Studio and ArcGIS Pro to clean, analyze, and visualize data.

<br>
<br>

**Forestry Aide**: February 2018 - August 2020  
California State Parks | Oceano, CA  
<br>
_Responsibilities_: Field technician in the Habitat Monitoring System program assessing the effects of off highway vehicle activity on natural resources. Surveyed for small mammals, birds, fish, amphibians, plants, and intertidal invertebrates. Team leader for small mammal trapping study. Trained new employees and volunteers on species identification, animal handling, and ear tagging. Tracked kangaroo rats using radio telemetry collars to assess habitat utilization and survivorship.  

<br>
<br>  

**Environmental Services Intern**: March 2015 - February 2018  
California State Parks | Oceano, CA  
<br>
_Responsibilities_: Technician on CA least tern and western snowy plover monitoring and management project. Monitored nest and brood activity of western snowy plovers and California least terns. Tracked broods daily using color bands to assess nest success and chick survivorship. Surveyed and monitored activity of avian predators including peregrine falcons. Assisted with the rescuing of stranded marine mammals and birds 










